name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
     branches:
      - master

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: ⚙️ Install dependencies
        run: |
          go mod tidy
          sudo apt-get update
          sudo apt-get install -y
          sudo apt-get install libbtrfs-dev -y
          sudo apt-get install libgpgme-dev -y

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
          args: --timeout=5m
